services:
  - type: web
    name: grow-ui
    runtime: node
    rootDir: growui
    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeploy: true
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: PORT
        generateValue: true

